# This will expose port 25565 on your server.
# https://docker-minecraft-server.readthedocs.io/en/latest/
# Interactive configurator: https://setupmc.com/java-server/

services:
  minecraft:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
    volumes:
      - minecraft-data:/data

volumes:
  minecraft-data:
